# Lunch Money API Configuration
# Get your API key from https://my.lunchmoney.app/developers

# Your Lunch Money API key
lunchMoneyApiKey: "<YOUR_LUNCH_MONEY_API_KEY>"

rogers:
  # Rogers API Configuration
  username: "<YOUR_ROGERS_USERNAME>"
  password: "<YOUR_ROGERS_PASSWORD>"
  deviceId: "<FINGERPRINT_DEVICE_ID>"

